// list of subjects and units used
const subjects = ["Physics", "Chemistry", "Biology", "USABO", "ESS"];
const subjectUnitDictionary = {
    "Physics": ["Measurement",
        "Kinematics",
        "Linear Dynamics",
        "Statics",
        "Energy and Momentum",
        "Rotational Dynamics",
        "Simple Machines",
        "Gravitation",
        "Fluids",
        "Oscillations",
        "Wave and Sound Basics",
        "Ray Optics",
        "Wave Optics",
        "Thermodynamics",
        "Simple Machines",
        "Modern Physics",
        "Nuclear and Particle Physics",
        "Electrostatics",
        "Electric Conductors and Currents",
        "DC Circuits",
        "Induction and AC Circuits",
        "Magnetic Fields and Forces",
        "Electromagnetic Waves",
        "Astrophysics",
        "Lab Skills",
        "Calculus-Based"
    ],
    "Chemistry": ["Measurement",
        "Atomic Structure",
        "Compound Nomenclature",
        "Stoichiometry",
        "Solutions",
        "Types of Reactions",
        "Gases",
        "Thermochemistry",
        "Atomic Periodicity",
        "Atomic Bonding",
        "Liquids and Solids",
        "Kinetics",
        "Chemical Equilibria",
        "Acids and Bases",
        "Electrochemistry",
        "Nuclear Chemistry",
        "Coordination Chemistry",
        "Organic Chemistry",
        "Biochemistry",
        "Lab Skills"
    ],
    "Biology": ["Molecular Biology",
        "Cell Biology",
        "Metabolism",
        "Heredity and Genetics",
        "Evolution",
        "Biosystematics and Biodiversity",
        "Ecology",
        "Human Anatomy and Physiology",
        "Plant Anatomy and Physiology",
        "Lab Skills"
    ],
    "USABO": ["Animal Anatomy and Physiology", 
    "Plant Anatomy and Physiology", 
    "Cell Biology", 
    "Genetics and Evolution", 
    "Ecology", 
    "Ethology", 
    "Biosystematics"
    ],
    "ESS": ["Unit 1",
    "Unit 2",
    "Unit 3"]
};

module.exports = { subjectUnitDictionary: subjectUnitDictionary, subjects: subjects };
