// list of subjects and units used
const subjects = ["Physics", "Chemistry", "Biology"];
const subjectUnitDictionary = {
    "Physics": ["Measurement",
        "Kinematics",
        "Newton's Laws",
        "Forces",
        "Linear Momentum",
        "Rotation",
        "Energy Basics",
        "Gravitation",
        "Fluids",
        "Oscillations",
        "Wave Motion",
        "Sound",
        "Ray Optics",
        "Wave Opticcs",
        "Thermodynamics",
        "Simple Machines",
        "Modern Physics",
        "Nuclear Physics",
        "Electric Fields and Forces",
        "Electrical Properties of Materials",
        "Capacitors",
        "DC Circuits",
        "AC Circuits",
        "Magnetic Fields",
        "Magnetic Forces",
        "Induction",
        "Magnetic Properties of Materials",
        "Electromagnetic Waves - Advanced",
        "Lab Skills",
        "Astrophysics",
        "Calculus-Based"
    ],
    "Chemistry": ["Measurement",
        "Atomic Structure",
        "Compound Nomenclature",
        "Stoichiometry",
        "Solutions",
        "Types of Reactions",
        "Gases",
        "Thermochemistry",
        "Atomic Periodicity",
        "Atomic Bonding",
        "Liquids and Solids",
        "Kinetics",
        "Chemical Equilibria",
        "Acids and Bases",
        "Physical Chemistry",
        "Electrochemistry",
        "Nuclear Chemistry",
        "Coordination Chemistry",
        "Organic Chemistry",
        "Biochemistry",
        "Lab Skills"
    ],
    "Biology": ["Molecular Biology",
        "Cell Biology",
        "Metabolism",
        "Heredity and Genetics",
        "Evolution",
        "Biosystematics",
        "Ecology",
        "Human Anatomy and Physiology",
        "Plant Anatomy and Physiology",
        "Lab Skills"
    ]
};

module.exports = { subjectUnitDictionary: subjectUnitDictionary, subjects: subjects };
