// list of subjects and units used
const subjects = ["Physics", "Chemistry", "Biology"];
const subjectUnitDictionary = {
    "Physics": ["Measurement",
        "Kinematics",
        "Newton's Laws",
        "Forces",
        "Linear Momentum",
        "Rotation",
        "Energy Basics",
        "Gravitation",
        "Fluids",
        "Oscillations",
        "Wave Motion",
        "Sound",
        "Ray Optics",
        "Wave Opticcs",
        "Thermodynamics",
        "Simple Machines",
        "Modern Physics",
        "Nuclear Physics",
        "Electric Fields and Forces",
        "Electrical Properties of Materials",
        "Capacitors",
        "DC Circuits",
        "AC Circuits",
        "Magnetic Fields",
        "Magnetic Forces",
        "Induction",
        "Magnetic Properties of Materials",
        "Electromagnetic Waves - Advanced",
        "Lab Skills",
        "Astrophysics",
        "Calculus-Based"
    ],
    "Chemistry": ["Stoichiometry",
        "Gases",
        "Thermochemistry",
        "Atoms, Molecules, and Ions",
        "Solutions",
        "Atomic Structure",
        "Bonding",
        "Chemical Kinetics",
        "Chemical Equilibrium",
        "Acids and Bases",
        "Solubility",
        "Spontaneity, Entropy, and Free Energy",
        "Electrochemistry",
        "Organic Chemistry",
        "Chemical Reactions",
        "Materials Chemistry",
        "Biochemistry",
        "Lab Skills",
        "Physical Chemistry"                  
    ],
    "Biology": ["Molecular Biology",
        "Cell Biology",
        "Metabolism",
        "Heredity and Genetics",
        "Evolution",
        "Biosystematics",
        "Ecology",
        "Human Anatomy and Physiology",
        "Plant Anatomy and Physiology",
        "Lab Skills"
    ]
};

module.exports = { subjectUnitDictionary: subjectUnitDictionary, subjects: subjects };
